apiVersion: v1
kind: Pod
metadata:
  name: multitool-client
  labels:
    app: multitool-client
spec:
  restartPolicy: Never
  containers:
    - name: multitool
      image: wbitt/network-multitool
      command:
        - sh
        - -c
        - sleep 3600
