apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-service
  labels:
    app: nginx-multitool
spec:
  type: ClusterIP
  selector:
    app: nginx-multitool
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http-nginx
