apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-clusterip
  labels:
    app: nginx-multitool
spec:
  type: ClusterIP
  selector:
    app: nginx-multitool
  ports:
    - name: nginx
      protocol: TCP
      port: 9001
      targetPort: http-nginx

    - name: multitool
      protocol: TCP
      port: 9002
      targetPort: http-multitool
